# From mmdetection3d
ARG PYTORCH="1.9.1"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX" \
    TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    FORCE_CUDA="1"

# Avoid Public GPG key error
# https://github.com/NVIDIA/nvidia-docker/issues/1631
RUN rm /etc/apt/sources.list.d/cuda.list \
    && rm /etc/apt/sources.list.d/nvidia-ml.list \
    && apt-key del 7fa2af80 \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub \
    && apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

# (Optional, use Mirror to speed up downloads)
# RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/mirrors.aliyun.com\/ubuntu\//g' /etc/apt/sources.list && \
#    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# Install the required packages
RUN apt-get update \
    && apt-get install -y ffmpeg libsm6 libxext6 wget git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Sparse4D
# Most requirements are already given. 
# requirement.txt causes issues with versions, maybe another base image could fix?

#COPY /requirement.txt /sparse4d/requirement.txt
#RUN pip install -r /sparse4d/requirement.txt
RUN pip install torch==1.9.1+cu111 \
            torchvision==0.10.1+cu111 \
            torchaudio==0.9.1 \
            -f https://download.pytorch.org/whl/torch_stable.html

RUN pip install numba==0.53.1
RUN pip install numpy==1.19.5
RUN pip install nuscenes-devkit==1.1.9
RUN pip install mmcv==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
RUN pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
RUN pip install mmdet==2.19.1

RUN git clone --branch v1.0.0rc0 https://github.com/open-mmlab/mmdetection3d.git /mmdetection3d
WORKDIR /mmdetection3d
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .

RUN pip install mmsegmentation==0.20.2
RUN pip install motmetrics==1.1.3
RUN pip install tensorboard==2.6.0

RUN pip install torchmetrics==0.5.0

# https://github.com/open-mmlab/mmdetection/issues/10962
RUN pip install yapf==0.40.1

WORKDIR /sparse4d

COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]